### ISSUE TITLE
json object keys are not ordered

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/sPlot#3]
Noticed during comparative testing.

These records were both generated with the container (under singularity):

* `{"bp_change_counts":{},"version":"1.3.0","analysis":"caveman_c","mutation_counts":{},"sample":"PD26840a"}`
* `{"version":"1.3.0","analysis":"caveman_c","sample":"PD26840a","bp_change_counts":{},"mutation_counts":{}}`

Need to use [`canonical`](https://metacpan.org/pod/JSON#canonical) mode for output to produce stable object.

**Comment by keiranmraine** [comment]
@byb121 I suspect our internal CI was "lucky" to not hit this.

**Comment by keiranmraine** [comment]
Had been worked around in the internal CI, removed workaround.

**Comment by byb121** [comment]
@keiranmraine CI compare results after sorting keys in json.

**Comment by keiranmraine** [comment]
@byb121, yes hence why we weren't aware the file output wasn't stable.  Makes it very difficult to generate reports of equivalence from the DB (as it's loaded as a CLOB) with some of the entries been many kb.
